kind: pipeline
name: automatic-image-update

steps:
  - name: tag-preparation
    image: alpine
    commands:
      - echo "tag $(date -u +%d.%m.%y)"
      - echo -n $(date -u +%d.%m.%y) > .tags

  - name: docker-build-push
    image: plugins/docker
    settings:
      repo: lynnier/dragory-modmail
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
