kind: pipeline
name: automatic-image-update

steps:
  - name: build-docker
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - export TAG_TIME=$(date -u +%d.%m.%y)
      - docker build -t docker.io/lynnier/dragory-modmail:$TAG_TIME .

  - name: push-docker
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      USER:
        from_secret: dockerhub_user
      PASS:
        from_secret: dockerhub_pass
    commands:
      - export TAG_TIME=$(date -u +%d.%m.%y)
      - docker login -u $USER -p $PASS
      - docker push docker.io/lynnier/dragory-modmail:$TAG_TIME

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
